name: First Workflow
# Defines event or trigger in which the workflow should run
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: |
            echo "Hello World!"
            echo "another line!"
      - name: Print goodbye
        run: echo "Done - bye!"
        
